# Generated by Django 5.2.4 on 2025-09-06 21:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotmine", "0002_investment"),
    ]

    operations = [
        migrations.CreateModel(
            name="CryptoWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wallet_type",
                    models.CharField(
                        choices=[
                            ("BTC", "Bitcoin"),
                            ("ETH", "Ethereum"),
                            ("BNB", "Binance Coin"),
                            ("USDT", "Tether (TRC20)"),
                            ("LTC", "Litecoin"),
                            ("ADA", "Cardano"),
                            ("DOT", "Polkadot"),
                            ("SOL", "Solana"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("wallet_address", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Crypto Wallet",
                "verbose_name_plural": "Crypto Wallets",
            },
        ),
        migrations.AlterModelOptions(
            name="investment",
            options={
                "ordering": ["-date_invested"],
                "verbose_name": "Investment",
                "verbose_name_plural": "Investments",
            },
        ),
        migrations.AddField(
            model_name="investment",
            name="date_completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="investment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="total_earnings",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="investment",
            name="wallet_address_used",
            field=models.CharField(
                blank=True,
                help_text="Wallet address that was used for this investment",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="plan",
            field=models.CharField(
                blank=True,
                help_text="Legacy field - use investment_plan instead",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="wallet_address",
            field=models.CharField(
                blank=True,
                help_text="Legacy field - use wallet_address_used instead",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="InvestmentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "minimum_deposit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "maximum_deposit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "daily_earnings_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Daily earnings percentage (e.g., 1.80 for 1.8%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.01),
                            django.core.validators.MaxValueValidator(50.0),
                        ],
                    ),
                ),
                (
                    "investment_duration_days",
                    models.PositiveIntegerField(
                        help_text="Investment duration in days"
                    ),
                ),
                (
                    "deposit_return",
                    models.BooleanField(
                        default=True, help_text="Return initial deposit after duration"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order to display plans (lower numbers first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crypto_wallet",
                    models.ForeignKey(
                        help_text="Crypto wallet for this plan",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotmine.cryptowallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Investment Plan",
                "verbose_name_plural": "Investment Plans",
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.AddField(
            model_name="investment",
            name="investment_plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hotmine.investmentplan",
            ),
        ),
    ]
