# Generated by Django 5.2.4 on 2025-09-06 21:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotmine", "0003_cryptowallet_alter_investment_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptowallet",
            name="wallet_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cryptowallet",
            name="wallet_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BTC", "Bitcoin"),
                    ("ETH", "Ethereum"),
                    ("BNB", "Binance Coin"),
                    ("USDT", "Tether (TRC20)"),
                    ("LTC", "Litecoin"),
                    ("ADA", "Cardano"),
                    ("DOT", "Polkadot"),
                    ("SOL", "Solana"),
                ],
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="investment_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hotmine.investmentplan",
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="plan",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="investment",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="total_earnings",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="wallet_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="investmentplan",
            name="crypto_wallet",
            field=models.ForeignKey(
                blank=True,
                help_text="Crypto wallet for this plan",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hotmine.cryptowallet",
            ),
        ),
        migrations.AlterField(
            model_name="investmentplan",
            name="daily_earnings_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Daily earnings percentage (e.g., 1.80 for 1.8%)",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.01),
                    django.core.validators.MaxValueValidator(50.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="investmentplan",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="investmentplan",
            name="investment_duration_days",
            field=models.PositiveIntegerField(
                blank=True, help_text="Investment duration in days", null=True
            ),
        ),
        migrations.AlterField(
            model_name="investmentplan",
            name="minimum_deposit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="investmentplan",
            name="sort_order",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Order to display plans (lower numbers first)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="investmentplan",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
