# Generated by Django 5.2.4 on 2025-09-07 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotmine", "0005_transaction"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
