# Generated by Django 5.2.4 on 2025-09-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotmine", "0008_withdrawalrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="withdrawal_disabled_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason for disabling withdrawals (optional)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="withdrawal_enabled",
            field=models.BooleanField(
                default=True, help_text="Allow this user to make withdrawal requests"
            ),
        ),
    ]
