# Generated by Django 5.2.4 on 2025-09-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotmine", "0009_userprofile_withdrawal_disabled_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="withdrawal_enabled",
            field=models.BooleanField(
                default=False, help_text="Allow this user to make withdrawal requests"
            ),
        ),
    ]
